### PR TITLE
XENON1T Binwise likelihood implementation

### PR DESCRIPTION
**Pull request by kdund**
This implements https://doi.org/10.1140/epjc/s10052-022-10913-w : the approximate binwise likelihood for XENON1T. 
Unlike the regular XENON1T results, this was designed to give an approximate likelihood for any nuclear recoil spectra-- spin independent/dependent/ETF or whatnot. 

The implementation required: 
 - To create a new file declaring the migration matrix and likelihood table for this analysis
 - to add these as possible members of DetectorStruct
 - and to add a new StatisticsFlag =3, which leads the likelihood computation to use a new BinwiseLikelihood function to compute the likelihood. Called from python, the calls take 0.2ms each. 

Have checked: [x] that the computation for a given array of expected events agrees with the python implementation
      [x] that the migration matrix is correct (need to print out the DDCalc recoil spectrum) 

Possible extensions: 
- We have the same format for the full 20ty XENONnT projection-- however, in that case, there are 1000 toyMC result files that would have to be read in-- at runtime?

### CODE REVIEW

**Comment by kdund** [comment]
Update: 
Both the signal folding and likelihood evaluation agree exactly between the implementation, see attached plots: 

image


image


Script to do this checking is attached as a [jupyter notebook](https://github.com/kdund/ddcalc_test/blob/main/binwise_ddcalc_verification.ipynb)  (you need the xenon binwise likelihood, installed via pip install xe-likelihood, plus setting your DDCalc include directory)

**Comment by kdund** [comment]
Concern about timing: 
- DDCalc took 38ms for 200 likelihood evaluations (200 steps / 5240 steps/s)
- Python took 2ms for the same. (80steps / 36000 steps/s)
The python operates with array-wise operations, so presumably that is an important driver of speed-- this may not be possible when you're finding intersections, or evaluating one likelihood per walker point?

**Comment by kahlhoefer** [comment]
Hi Knut,
Thanks a lot for all the work - this looks really promising! However, is it possible that you forgot to push  XENON1T_2022.f90 ? I also don't currently see how the lltable is actually filled. Is there another file missing?
Cheers,
Felix

**Comment by kdund** [comment]
Hi, @kahlhoefer sorry indeed-- beginner mistake :D

**Comment by kahlhoefer** [comment]
Hi Knut,
This looks awesome! Thanks so much for the implementation and apologies for the very slow review. I only have one comment: In DDCalc and GAMBIT, when we say LogLikelihood, we (somewhat confusingly) actually mean log(L), not -2 log(L). In particular the LogLikelihood should typically get smaller (i.e. more negative) for increasing cross sections. I think your current implementation uses the (more common) convention that LogLikelihood means -2 log(L). Can you fix that, or should I do it?
Best,
Felix

**Comment by kdund** [comment]
Hi, @kahlhoefer , 2x in (and checked with the https://github.com/kdund/ddcalc_test/blob/main/binwise_ddcalc_verification.ipynb jupyter notebook that it gives the same result when you multiply with -2)

**Pull request merged**
